CREATE TABLE IF NOT EXISTS booking (
    id SERIAL PRIMARY KEY,
    flight_number VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    updated_at DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
);