CREATE TABLE IF NOT EXISTS user_details (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    phone_no VARCHAR(20) NOT NULL UNIQUE,
    updated_at DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
